INSERT INTO GENEROS(NOMBRE) VALUES('Accion');
INSERT INTO GENEROS(NOMBRE) VALUES('Comedia');
INSERT INTO GENEROS(NOMBRE) VALUES('Drama');
INSERT INTO GENEROS(NOMBRE) VALUES('Fantasia');
INSERT INTO GENEROS(NOMBRE) VALUES('Terror');

INSERT INTO ACTORES(NOMBRE,URL_IMAGEN) VALUES('Hugh Jackman','https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/actor-hugh-jackman-is-sighted-on-the-club-55-beach-on-july-news-photo-1645092773.jpg?crop=1.00xw:0.754xh;0,0.0744xh&resize=640:*');
INSERT INTO ACTORES(NOMBRE,URL_IMAGEN) VALUES('Keanu Reeves','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBp84zLLGL0pdG2BzM4C1NxUbelaDhRQvdQw&usqp=CAU');


INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('anaconda',1,'2022-01-01');
INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('survivol',5,'2022-01-01');
INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('despertar',1,'2022-01-01');
INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('spiderman',1,'2022-01-01');
INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('anaconda 2',1,'2022-01-01');
INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('naruto',1,'2022-01-01');
INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('anaconda 3',1,'2022-01-01');
INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('naruto',4,'2022-01-01');
INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('pow ',1,'2022-01-01');
INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('powe',5,'2022-01-01');
INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('coco',1,'2022-01-01');
INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('anaconda',1,'2022-01-01');
INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('blanca nieves',1,'2022-01-01');
INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('inframundo',1,'2022-01-01');
INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('harvey specter',1,'2022-01-01');
INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('lucifer',1,'2022-01-01');
INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('implacable',2,'2022-01-01');
INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('',21,'2022-01-01');
INSERT INTO PELICULAS(NOMBRE ,GENERO_ID, FECHA_ESTRENO) VALUES('rapidos y furios',2,'2022-01-01');
